/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensaje;
import cjb.ci.Validaciones;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristopher y Javier
 */
public class VentanaAltasCompania extends javax.swing.JFrame
{

    public Nodo n2;

    /**
     * Creates new form VentanaAltasAeropuerto
     */
    public VentanaAltasCompania()
    {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/Compania.jpg")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        letreroAgregarN1 = new javax.swing.JLabel();
        elementosNivel1 = new javax.swing.JComboBox<>();
        letreroAgregarN2 = new javax.swing.JLabel();
        elementosNivel2 = new javax.swing.JComboBox<>();
        nombreCompania = new javax.swing.JLabel();
        nomCompania = new javax.swing.JTextField();
        urlCompania = new javax.swing.JLabel();
        url = new javax.swing.JTextField();
        parentesis1 = new javax.swing.JLabel();
        telefono2 = new javax.swing.JTextField();
        telefono1 = new javax.swing.JTextField();
        agregarImagen = new javax.swing.JButton();
        correoElectronico = new javax.swing.JLabel();
        correoElec = new javax.swing.JTextField();
        aceptar = new javax.swing.JButton();
        ftCompania = new javax.swing.JLabel();
        cancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Altas Compañias");
        setMinimumSize(new java.awt.Dimension(925, 420));
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        letreroAgregarN1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        letreroAgregarN1.setForeground(new java.awt.Color(0, 0, 102));
        letreroAgregarN1.setText("Agregar al aeropuerto:");
        getContentPane().add(letreroAgregarN1);
        letreroAgregarN1.setBounds(43, 20, 210, 38);

        elementosNivel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        elementosNivel1.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                elementosNivel1ItemStateChanged(evt);
            }
        });
        getContentPane().add(elementosNivel1);
        elementosNivel1.setBounds(40, 60, 260, 38);

        letreroAgregarN2.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        letreroAgregarN2.setForeground(new java.awt.Color(0, 0, 102));
        letreroAgregarN2.setText("Agregar al destino:");
        getContentPane().add(letreroAgregarN2);
        letreroAgregarN2.setBounds(40, 120, 174, 38);

        elementosNivel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        getContentPane().add(elementosNivel2);
        elementosNivel2.setBounds(40, 160, 260, 38);

        nombreCompania.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        nombreCompania.setForeground(new java.awt.Color(0, 0, 102));
        nombreCompania.setText("Nombre de la compañia:");
        getContentPane().add(nombreCompania);
        nombreCompania.setBounds(40, 220, 230, 38);

        nomCompania.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        nomCompania.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                nomCompaniaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                nomCompaniaKeyTyped(evt);
            }
        });
        getContentPane().add(nomCompania);
        nomCompania.setBounds(40, 260, 260, 38);

        urlCompania.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        urlCompania.setForeground(new java.awt.Color(0, 0, 102));
        urlCompania.setText("URL:");
        getContentPane().add(urlCompania);
        urlCompania.setBounds(350, 20, 80, 38);

        url.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        url.setEnabled(false);
        url.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                urlKeyPressed(evt);
            }
        });
        getContentPane().add(url);
        url.setBounds(350, 60, 260, 38);

        parentesis1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        parentesis1.setForeground(new java.awt.Color(0, 0, 102));
        parentesis1.setText("Teléfono:");
        getContentPane().add(parentesis1);
        parentesis1.setBounds(350, 120, 120, 39);

        telefono2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        telefono2.setEnabled(false);
        telefono2.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                telefono2KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                telefono2KeyTyped(evt);
            }
        });
        getContentPane().add(telefono2);
        telefono2.setBounds(410, 160, 200, 39);

        telefono1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        telefono1.setEnabled(false);
        telefono1.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                telefono1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                telefono1KeyTyped(evt);
            }
        });
        getContentPane().add(telefono1);
        telefono1.setBounds(350, 160, 50, 39);

        agregarImagen.setBackground(new java.awt.Color(255, 255, 255));
        agregarImagen.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        agregarImagen.setForeground(new java.awt.Color(0, 0, 102));
        agregarImagen.setText("Agregar");
        agregarImagen.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                agregarImagenActionPerformed(evt);
            }
        });
        agregarImagen.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                agregarImagenKeyPressed(evt);
            }
        });
        getContentPane().add(agregarImagen);
        agregarImagen.setBounds(720, 270, 90, 23);

        correoElectronico.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        correoElectronico.setForeground(new java.awt.Color(0, 0, 102));
        correoElectronico.setText("Correo electrónico:");
        getContentPane().add(correoElectronico);
        correoElectronico.setBounds(350, 220, 180, 39);

        correoElec.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        correoElec.setEnabled(false);
        correoElec.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                correoElecKeyPressed(evt);
            }
        });
        getContentPane().add(correoElec);
        correoElec.setBounds(350, 260, 260, 39);

        aceptar.setBackground(new java.awt.Color(255, 255, 255));
        aceptar.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        aceptar.setForeground(new java.awt.Color(0, 0, 102));
        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                aceptarActionPerformed(evt);
            }
        });
        aceptar.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                aceptarKeyPressed(evt);
            }
        });
        getContentPane().add(aceptar);
        aceptar.setBounds(800, 340, 90, 23);

        ftCompania.setBackground(new java.awt.Color(255, 255, 255));
        ftCompania.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        ftCompania.setForeground(new java.awt.Color(0, 0, 102));
        ftCompania.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ftCompania.setText("FOTO");
        ftCompania.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 10));
        getContentPane().add(ftCompania);
        ftCompania.setBounds(650, 30, 220, 220);

        cancelar.setBackground(new java.awt.Color(255, 255, 255));
        cancelar.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        cancelar.setForeground(new java.awt.Color(0, 0, 102));
        cancelar.setText("Limpiar");
        cancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(cancelar);
        cancelar.setBounds(670, 340, 90, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 910, 390);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        ManipulaMultista.cargaCombo(VentanaPrincipal.r, elementosNivel1);
    }//GEN-LAST:event_formWindowOpened

    private void elementosNivel1ItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_elementosNivel1ItemStateChanged
    {//GEN-HEADEREND:event_elementosNivel1ItemStateChanged
        n2 = ManipulaMultista.busca(VentanaPrincipal.r, (String) elementosNivel1.getSelectedItem());
        ManipulaMultista.cargaCombo(n2.getAbajo(), elementosNivel2);
    }//GEN-LAST:event_elementosNivel1ItemStateChanged

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelarActionPerformed
    {//GEN-HEADEREND:event_cancelarActionPerformed
        CtrlInterfaz.limpia(nomCompania, url, telefono1, telefono2, correoElec);
        CtrlInterfaz.habilita(false, url, telefono1, telefono2, correoElec);
        ftCompania.setIcon(null);

        CtrlInterfaz.cambia(nomCompania);
    }//GEN-LAST:event_cancelarActionPerformed

    private void aceptarKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_aceptarKeyPressed
    {//GEN-HEADEREND:event_aceptarKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            aceptarActionPerformed(null);
        }
    }//GEN-LAST:event_aceptarKeyPressed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_aceptarActionPerformed
    {//GEN-HEADEREND:event_aceptarActionPerformed
        try
        {
            String nC = nomCompania.getText().trim();
            String u = url.getText().trim();
            String t1 = telefono1.getText().trim();
            String t2 = telefono2.getText().trim();
            String cE = correoElec.getText().trim();
            if (nC.length() == 0 || u.length() == 0 || t1.length() == 0 || t2.length() == 0 || cE.length() == 0 || ftCompania.getIcon() == null)
            {
                JOptionPane.showMessageDialog(this, "Hay datos sin llenar", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
            } else
            {
                String numeroCadeda1 = telefono1.getText();
                String numeroCadeda2 = telefono2.getText();
                long numeroEntero1 = Integer.parseInt(numeroCadeda1);
                long numeroEntero2 = Integer.parseInt(numeroCadeda2);
                Compania cpn = new Compania(nomCompania.getText(), url.getText(), numeroEntero1, numeroEntero2, correoElec.getText(), ftCompania.getIcon());
                Nodo nd = new Nodo(cpn, nomCompania.getText());
                String s[] = new String[3];
                s[0] = (String) elementosNivel1.getSelectedItem();
                s[1] = (String) elementosNivel2.getSelectedItem();
                s[2] = nomCompania.getText();
                VentanaPrincipal.r = ManipulaMultista.inserta(VentanaPrincipal.r, nd, s, 0);
                NodoArbol ndA = new NodoArbol(nomCompania.getText());
                ndA.setHh(nd);
                VentanaPrincipal.aR3.setR(VentanaPrincipal.aR3.inserta(VentanaPrincipal.aR3.getR(), ndA));
                Mensaje.exito(this, "Dato insertado correctamente");
                cancelarActionPerformed(null);
            }
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Error", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
            cancelarActionPerformed(null);
        }
    }//GEN-LAST:event_aceptarActionPerformed

    private void telefono1KeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_telefono1KeyTyped
    {//GEN-HEADEREND:event_telefono1KeyTyped
        Validaciones.validaEntero(evt);
    }//GEN-LAST:event_telefono1KeyTyped

    private void telefono1KeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_telefono1KeyPressed
    {//GEN-HEADEREND:event_telefono1KeyPressed
        Validaciones.enterEntero(this, evt, telefono1, telefono2);
        Validaciones.limite(telefono1, 3);
    }//GEN-LAST:event_telefono1KeyPressed

    private void correoElecKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_correoElecKeyPressed
    {//GEN-HEADEREND:event_correoElecKeyPressed
        Validaciones.enter(this, evt, agregarImagen);
        Validaciones.limite(correoElec, 30);
    }//GEN-LAST:event_correoElecKeyPressed

    private void urlKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_urlKeyPressed
    {//GEN-HEADEREND:event_urlKeyPressed
        Validaciones.enter(this, evt, telefono1);
        Validaciones.limite(url, 40);
    }//GEN-LAST:event_urlKeyPressed

    private void nomCompaniaKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nomCompaniaKeyTyped
    {//GEN-HEADEREND:event_nomCompaniaKeyTyped
        // KeyTyped es para validar entrada de datos
        Validaciones.validaAlfabeticos(evt);
    }//GEN-LAST:event_nomCompaniaKeyTyped

    private void nomCompaniaKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nomCompaniaKeyPressed
    {//GEN-HEADEREND:event_nomCompaniaKeyPressed
        // KeyPressed es para validar el enter
        Validaciones.enter(this, evt, url);
        Validaciones.limite(nomCompania, 30);
    }//GEN-LAST:event_nomCompaniaKeyPressed

    private void agregarImagenActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_agregarImagenActionPerformed
    {//GEN-HEADEREND:event_agregarImagenActionPerformed
        new VentanaFotosCarga(ftCompania).setVisible(true);
    }//GEN-LAST:event_agregarImagenActionPerformed

    private void agregarImagenKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_agregarImagenKeyPressed
    {//GEN-HEADEREND:event_agregarImagenKeyPressed
        new VentanaFotosCarga(ftCompania).setVisible(true);
    }//GEN-LAST:event_agregarImagenKeyPressed

    private void telefono2KeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_telefono2KeyPressed
    {//GEN-HEADEREND:event_telefono2KeyPressed
        Validaciones.enterEntero(this, evt, telefono2, correoElec);
        Validaciones.limite(telefono2, 7);
    }//GEN-LAST:event_telefono2KeyPressed

    private void telefono2KeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_telefono2KeyTyped
    {//GEN-HEADEREND:event_telefono2KeyTyped
        Validaciones.validaEntero(evt);
    }//GEN-LAST:event_telefono2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VentanaAltasCompania.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VentanaAltasCompania.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VentanaAltasCompania.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VentanaAltasCompania.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                new VentanaAltasCompania().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JButton agregarImagen;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField correoElec;
    private javax.swing.JLabel correoElectronico;
    private javax.swing.JComboBox<String> elementosNivel1;
    private javax.swing.JComboBox<String> elementosNivel2;
    private javax.swing.JLabel ftCompania;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel letreroAgregarN1;
    private javax.swing.JLabel letreroAgregarN2;
    private javax.swing.JTextField nomCompania;
    private javax.swing.JLabel nombreCompania;
    private javax.swing.JLabel parentesis1;
    private javax.swing.JTextField telefono1;
    private javax.swing.JTextField telefono2;
    private javax.swing.JTextField url;
    private javax.swing.JLabel urlCompania;
    // End of variables declaration//GEN-END:variables
}
