/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensaje;
import cjb.ci.Validaciones;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristopher
 */
public class VentanaAltasVuelos extends javax.swing.JFrame
{

    public Nodo n2, n3;

    /**
     * Creates new form VentanaAltasAeropuerto
     */
    public VentanaAltasVuelos()
    {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/Vuelo.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        letreroAgregarN1 = new javax.swing.JLabel();
        elementosNivel1 = new javax.swing.JComboBox<>();
        letreroAgregarN2 = new javax.swing.JLabel();
        elementosNivel2 = new javax.swing.JComboBox<>();
        letreroAgregarN3 = new javax.swing.JLabel();
        elementosNivel3 = new javax.swing.JComboBox<>();
        numeroVuelo = new javax.swing.JLabel();
        numVuelo = new javax.swing.JTextField();
        horaSalida = new javax.swing.JLabel();
        puntosHoraSalida = new javax.swing.JLabel();
        horaLlegada = new javax.swing.JLabel();
        puntosHoraLlegada = new javax.swing.JLabel();
        precioVuelo = new javax.swing.JLabel();
        precio = new javax.swing.JTextField();
        numeroAsientosFila = new javax.swing.JLabel();
        numAsientosFila = new javax.swing.JTextField();
        numeroFilas = new javax.swing.JLabel();
        numFilas = new javax.swing.JTextField();
        aceptar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        simboloDinero = new javax.swing.JLabel();
        horasLlegada = new javax.swing.JComboBox<>();
        horasSalida = new javax.swing.JComboBox<>();
        minutosSalida = new javax.swing.JComboBox<>();
        minutosLlegada = new javax.swing.JComboBox<>();
        agregarImagen = new javax.swing.JButton();
        ftVuelos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Altas Vuelos");
        setMinimumSize(new java.awt.Dimension(890, 500));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        letreroAgregarN1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        letreroAgregarN1.setForeground(new java.awt.Color(0, 0, 102));
        letreroAgregarN1.setText("Agregar al aeropuerto:");
        getContentPane().add(letreroAgregarN1);
        letreroAgregarN1.setBounds(40, 20, 210, 38);

        elementosNivel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        elementosNivel1.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                elementosNivel1ItemStateChanged(evt);
            }
        });
        getContentPane().add(elementosNivel1);
        elementosNivel1.setBounds(40, 60, 260, 38);

        letreroAgregarN2.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        letreroAgregarN2.setForeground(new java.awt.Color(0, 0, 102));
        letreroAgregarN2.setText("Agregar al destino:");
        getContentPane().add(letreroAgregarN2);
        letreroAgregarN2.setBounds(40, 120, 174, 38);

        elementosNivel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        elementosNivel2.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                elementosNivel2ItemStateChanged(evt);
            }
        });
        getContentPane().add(elementosNivel2);
        elementosNivel2.setBounds(40, 160, 260, 38);

        letreroAgregarN3.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        letreroAgregarN3.setForeground(new java.awt.Color(0, 0, 102));
        letreroAgregarN3.setText("Agregar a la compania:");
        getContentPane().add(letreroAgregarN3);
        letreroAgregarN3.setBounds(40, 220, 220, 38);

        elementosNivel3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        getContentPane().add(elementosNivel3);
        elementosNivel3.setBounds(40, 260, 260, 38);

        numeroVuelo.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        numeroVuelo.setForeground(new java.awt.Color(0, 0, 102));
        numeroVuelo.setText("Número de vuelo:");
        getContentPane().add(numeroVuelo);
        numeroVuelo.setBounds(350, 120, 150, 38);

        numVuelo.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        numVuelo.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                numVueloKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                numVueloKeyTyped(evt);
            }
        });
        getContentPane().add(numVuelo);
        numVuelo.setBounds(350, 160, 80, 38);

        horaSalida.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        horaSalida.setForeground(new java.awt.Color(0, 0, 102));
        horaSalida.setText("Hora de salida:");
        getContentPane().add(horaSalida);
        horaSalida.setBounds(40, 320, 130, 38);

        puntosHoraSalida.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        puntosHoraSalida.setForeground(new java.awt.Color(0, 0, 102));
        puntosHoraSalida.setText("$");
        puntosHoraSalida.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(puntosHoraSalida);
        puntosHoraSalida.setBounds(430, 260, 20, 40);

        horaLlegada.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        horaLlegada.setForeground(new java.awt.Color(0, 0, 102));
        horaLlegada.setText("Hora de llegada:");
        getContentPane().add(horaLlegada);
        horaLlegada.setBounds(350, 20, 140, 38);

        puntosHoraLlegada.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        puntosHoraLlegada.setForeground(new java.awt.Color(0, 0, 102));
        puntosHoraLlegada.setText(":");
        puntosHoraLlegada.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(puntosHoraLlegada);
        puntosHoraLlegada.setBounds(410, 60, 11, 40);

        precioVuelo.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        precioVuelo.setForeground(new java.awt.Color(0, 0, 102));
        precioVuelo.setText("Precio:");
        getContentPane().add(precioVuelo);
        precioVuelo.setBounds(350, 220, 70, 39);

        precio.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        precio.setEnabled(false);
        precio.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                precioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                precioKeyTyped(evt);
            }
        });
        getContentPane().add(precio);
        precio.setBounds(350, 260, 80, 39);

        numeroAsientosFila.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        numeroAsientosFila.setForeground(new java.awt.Color(0, 0, 102));
        numeroAsientosFila.setText("Número de asientos por fila:");
        getContentPane().add(numeroAsientosFila);
        numeroAsientosFila.setBounds(350, 320, 230, 40);

        numAsientosFila.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        numAsientosFila.setEnabled(false);
        numAsientosFila.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                numAsientosFilaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                numAsientosFilaKeyTyped(evt);
            }
        });
        getContentPane().add(numAsientosFila);
        numAsientosFila.setBounds(350, 360, 80, 40);

        numeroFilas.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        numeroFilas.setForeground(new java.awt.Color(0, 0, 102));
        numeroFilas.setText("Número de filas:");
        getContentPane().add(numeroFilas);
        numeroFilas.setBounds(630, 20, 202, 40);

        numFilas.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        numFilas.setEnabled(false);
        numFilas.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                numFilasKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                numFilasKeyTyped(evt);
            }
        });
        getContentPane().add(numFilas);
        numFilas.setBounds(630, 60, 80, 40);

        aceptar.setBackground(new java.awt.Color(255, 255, 255));
        aceptar.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        aceptar.setForeground(new java.awt.Color(0, 0, 102));
        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                aceptarActionPerformed(evt);
            }
        });
        aceptar.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                aceptarKeyPressed(evt);
            }
        });
        getContentPane().add(aceptar);
        aceptar.setBounds(780, 430, 90, 23);

        cancelar.setBackground(new java.awt.Color(255, 255, 255));
        cancelar.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        cancelar.setForeground(new java.awt.Color(0, 0, 102));
        cancelar.setText("Limpiar");
        cancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(cancelar);
        cancelar.setBounds(650, 430, 90, 23);

        simboloDinero.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        simboloDinero.setForeground(new java.awt.Color(0, 0, 102));
        simboloDinero.setText(":");
        simboloDinero.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(simboloDinero);
        simboloDinero.setBounds(110, 360, 11, 40);

        horasLlegada.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        horasLlegada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));
        getContentPane().add(horasLlegada);
        horasLlegada.setBounds(350, 60, 60, 40);

        horasSalida.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        horasSalida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));
        getContentPane().add(horasSalida);
        horasSalida.setBounds(40, 360, 60, 40);

        minutosSalida.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        minutosSalida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        getContentPane().add(minutosSalida);
        minutosSalida.setBounds(130, 360, 60, 40);

        minutosLlegada.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        minutosLlegada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        getContentPane().add(minutosLlegada);
        minutosLlegada.setBounds(420, 60, 60, 40);

        agregarImagen.setBackground(new java.awt.Color(255, 255, 255));
        agregarImagen.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        agregarImagen.setForeground(new java.awt.Color(0, 0, 102));
        agregarImagen.setText("Agregar");
        agregarImagen.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                agregarImagenActionPerformed(evt);
            }
        });
        agregarImagen.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                agregarImagenKeyPressed(evt);
            }
        });
        getContentPane().add(agregarImagen);
        agregarImagen.setBounds(700, 360, 90, 23);

        ftVuelos.setBackground(new java.awt.Color(255, 255, 255));
        ftVuelos.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        ftVuelos.setForeground(new java.awt.Color(0, 0, 102));
        ftVuelos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ftVuelos.setText("FOTO");
        ftVuelos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 10));
        getContentPane().add(ftVuelos);
        ftVuelos.setBounds(630, 120, 220, 220);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 890, 480);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void numVueloKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_numVueloKeyPressed
    {//GEN-HEADEREND:event_numVueloKeyPressed
        // KeyPressed es para validar el enter
        Validaciones.enterEntero(this, evt, numVuelo, precio);
        Validaciones.limite(numVuelo, 5);
    }//GEN-LAST:event_numVueloKeyPressed

    private void numVueloKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_numVueloKeyTyped
    {//GEN-HEADEREND:event_numVueloKeyTyped
        // KeyTyped es para validar entrada de datos
        Validaciones.validaEntero(evt);
    }//GEN-LAST:event_numVueloKeyTyped

    private void precioKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_precioKeyPressed
    {//GEN-HEADEREND:event_precioKeyPressed
        Validaciones.enterFlotante(this, evt, precio, numAsientosFila);
        Validaciones.limite(precio, 8);
    }//GEN-LAST:event_precioKeyPressed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelarActionPerformed
    {//GEN-HEADEREND:event_cancelarActionPerformed
        CtrlInterfaz.limpia(numVuelo, precio, numAsientosFila, numFilas);
        CtrlInterfaz.habilita(false, precio, numAsientosFila, numFilas);
        CtrlInterfaz.cambia(numVuelo);
        ftVuelos.setIcon(null);
    }//GEN-LAST:event_cancelarActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_aceptarActionPerformed
    {//GEN-HEADEREND:event_aceptarActionPerformed
        try
        {
            String nV = numVuelo.getText().trim();
            String p = precio.getText().trim();
            String nAF = numAsientosFila.getText().trim();
            String nF = numFilas.getText().trim();
            if (nV.length() == 0 || p.length() == 0 || nAF.length() == 0 || nF.length() == 0 || ftVuelos.getIcon() == null)
            {
                JOptionPane.showMessageDialog(this, "Hay datos sin llenar", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
            } else
            {
                String numVueloCadeda = numVuelo.getText();
                int numVueloEntero = Integer.parseInt(numVueloCadeda);
                String horaSalidaC = (String) (horasSalida.getSelectedItem() + ":" + minutosSalida.getSelectedItem());
                String horaLlegadaC = (String) (horasLlegada.getSelectedItem() + ":" + minutosLlegada.getSelectedItem());
                String precioCadena = precio.getText();
                double precioFlotante = Double.parseDouble(precioCadena);
                String numAsientosFilaCadena = numAsientosFila.getText();
                int numAsientosFilaE = Integer.parseInt(numAsientosFilaCadena);
                String numFilasCadena = numFilas.getText();
                int numFilasE = Integer.parseInt(numFilasCadena);
                Vuelos vls = new Vuelos(numVueloEntero, horaSalidaC, horaLlegadaC, precioFlotante, numAsientosFilaE, numFilasE, ftVuelos.getIcon());
                Nodo nd = new Nodo(vls, numVueloCadeda);
                String s[] = new String[4];
                s[0] = (String) elementosNivel1.getSelectedItem();
                s[1] = (String) elementosNivel2.getSelectedItem();
                s[2] = (String) elementosNivel3.getSelectedItem();
                s[3] = (String) numVuelo.getText();
                VentanaPrincipal.r = ManipulaMultista.inserta(VentanaPrincipal.r, nd, s, 0);
                NodoArbol ndA = new NodoArbol(numVuelo.getText());
                ndA.setHh(nd);
                VentanaPrincipal.aR4.setR(VentanaPrincipal.aR4.inserta(VentanaPrincipal.aR4.getR(), ndA));
                Mensaje.exito(this, "Dato insertado correctamente");
                cancelarActionPerformed(null);
            }
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Seleccione niveles que tengan datos");
            cancelarActionPerformed(null);
        }
    }//GEN-LAST:event_aceptarActionPerformed

    private void aceptarKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_aceptarKeyPressed
    {//GEN-HEADEREND:event_aceptarKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            aceptarActionPerformed(null);
        }
    }//GEN-LAST:event_aceptarKeyPressed

    private void numAsientosFilaKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_numAsientosFilaKeyPressed
    {//GEN-HEADEREND:event_numAsientosFilaKeyPressed
        Validaciones.enterEntero(this, evt, numAsientosFila, numFilas);
        Validaciones.limite(numAsientosFila, 2);
    }//GEN-LAST:event_numAsientosFilaKeyPressed

    private void numFilasKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_numFilasKeyPressed
    {//GEN-HEADEREND:event_numFilasKeyPressed
        Validaciones.enterEntero(this, evt, numFilas, agregarImagen);
        Validaciones.limite(numFilas, 2);
    }//GEN-LAST:event_numFilasKeyPressed

    private void numAsientosFilaKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_numAsientosFilaKeyTyped
    {//GEN-HEADEREND:event_numAsientosFilaKeyTyped
        Validaciones.validaEntero(evt);
    }//GEN-LAST:event_numAsientosFilaKeyTyped

    private void precioKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_precioKeyTyped
    {//GEN-HEADEREND:event_precioKeyTyped
        Validaciones.validaFlotantes(evt);
    }//GEN-LAST:event_precioKeyTyped

    private void numFilasKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_numFilasKeyTyped
    {//GEN-HEADEREND:event_numFilasKeyTyped
        Validaciones.validaEntero(evt);
    }//GEN-LAST:event_numFilasKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        ManipulaMultista.cargaCombo(VentanaPrincipal.r, elementosNivel1);
    }//GEN-LAST:event_formWindowOpened

    private void elementosNivel2ItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_elementosNivel2ItemStateChanged
    {//GEN-HEADEREND:event_elementosNivel2ItemStateChanged
        try
        {
            n3 = ManipulaMultista.busca(n2.getAbajo(), (String) elementosNivel2.getSelectedItem());
            ManipulaMultista.cargaCombo(n3.getAbajo(), elementosNivel3);
        } catch (Exception e)
        {
            ManipulaMultista.cargaCombo(null, elementosNivel3);
        }
    }//GEN-LAST:event_elementosNivel2ItemStateChanged

    private void elementosNivel1ItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_elementosNivel1ItemStateChanged
    {//GEN-HEADEREND:event_elementosNivel1ItemStateChanged
        n2 = ManipulaMultista.busca(VentanaPrincipal.r, (String) elementosNivel1.getSelectedItem());
        ManipulaMultista.cargaCombo(n2.getAbajo(), elementosNivel2);
    }//GEN-LAST:event_elementosNivel1ItemStateChanged

    private void agregarImagenActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_agregarImagenActionPerformed
    {//GEN-HEADEREND:event_agregarImagenActionPerformed
        new VentanaFotosCarga(ftVuelos).setVisible(true);
    }//GEN-LAST:event_agregarImagenActionPerformed

    private void agregarImagenKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_agregarImagenKeyPressed
    {//GEN-HEADEREND:event_agregarImagenKeyPressed
        new VentanaFotosCarga(ftVuelos).setVisible(true);
    }//GEN-LAST:event_agregarImagenKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VentanaAltasVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VentanaAltasVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VentanaAltasVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VentanaAltasVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                new VentanaAltasVuelos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JButton agregarImagen;
    private javax.swing.JButton cancelar;
    private javax.swing.JComboBox<String> elementosNivel1;
    private javax.swing.JComboBox<String> elementosNivel2;
    private javax.swing.JComboBox<String> elementosNivel3;
    private javax.swing.JLabel ftVuelos;
    private javax.swing.JLabel horaLlegada;
    private javax.swing.JLabel horaSalida;
    private javax.swing.JComboBox<String> horasLlegada;
    private javax.swing.JComboBox<String> horasSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel letreroAgregarN1;
    private javax.swing.JLabel letreroAgregarN2;
    private javax.swing.JLabel letreroAgregarN3;
    private javax.swing.JComboBox<String> minutosLlegada;
    private javax.swing.JComboBox<String> minutosSalida;
    private javax.swing.JTextField numAsientosFila;
    private javax.swing.JTextField numFilas;
    private javax.swing.JTextField numVuelo;
    private javax.swing.JLabel numeroAsientosFila;
    private javax.swing.JLabel numeroFilas;
    private javax.swing.JLabel numeroVuelo;
    private javax.swing.JTextField precio;
    private javax.swing.JLabel precioVuelo;
    private javax.swing.JLabel puntosHoraLlegada;
    private javax.swing.JLabel puntosHoraSalida;
    private javax.swing.JLabel simboloDinero;
    // End of variables declaration//GEN-END:variables
}
