/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristopher y Javier
 */
public class VentanaModificaAeropuerto extends javax.swing.JFrame
{

    public static Nodo arrAer[];

    /**
     * Creates new form VentanaAltasAeropuerto
     */
    public VentanaModificaAeropuerto()
    {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/Aeropuerto.jpg")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        letreroEliminarN1 = new javax.swing.JLabel();
        elementosNivel1 = new javax.swing.JComboBox<>();
        modificar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificaciones Aeropuertos");
        setMinimumSize(new java.awt.Dimension(347, 215));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        letreroEliminarN1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        letreroEliminarN1.setForeground(new java.awt.Color(0, 0, 102));
        letreroEliminarN1.setText("Aeropuerto:");
        getContentPane().add(letreroEliminarN1);
        letreroEliminarN1.setBounds(40, 20, 110, 38);

        elementosNivel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        getContentPane().add(elementosNivel1);
        elementosNivel1.setBounds(40, 60, 260, 38);

        modificar.setBackground(new java.awt.Color(255, 255, 255));
        modificar.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        modificar.setForeground(new java.awt.Color(0, 0, 102));
        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                modificarActionPerformed(evt);
            }
        });
        getContentPane().add(modificar);
        modificar.setBounds(210, 140, 100, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 340, 190);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void modificarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_modificarActionPerformed
    {//GEN-HEADEREND:event_modificarActionPerformed
        NodoArbol d[] = new NodoArbol[2];
        try
        {
            String s[] = new String[1];
            s[0] = (String) elementosNivel1.getSelectedItem();
            arrAer = ManipulaMultista.elimina((String) elementosNivel1.getSelectedItem(), VentanaPrincipal.r, 0, s);
            VentanaPrincipal.r = arrAer[1];
            VentanaPrincipal.aR1.elimina(VentanaPrincipal.aR1.getR(), (String) elementosNivel1.getSelectedItem(), d);
            VentanaPrincipal.aR1.setR(d[1]);
            new VentanaModAeropuerto().setVisible(true);
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Error", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_modificarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        ManipulaMultista.cargaCombo(VentanaPrincipal.r, elementosNivel1);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VentanaModificaAeropuerto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VentanaModificaAeropuerto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VentanaModificaAeropuerto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VentanaModificaAeropuerto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                new VentanaModificaAeropuerto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> elementosNivel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel letreroEliminarN1;
    private javax.swing.JButton modificar;
    // End of variables declaration//GEN-END:variables
}
