/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Validaciones;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristopher y Javier
 */
public class VentanaBusquedaVuelos extends javax.swing.JFrame
{

    public Nodo n2, n3;

    /**
     * Creates new form VentanaAltasAeropuerto
     */
    public VentanaBusquedaVuelos()
    {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/Vuelo.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        numeroVuelo = new javax.swing.JLabel();
        hrSalida = new javax.swing.JTextField();
        hrLlegada = new javax.swing.JTextField();
        numVuelo = new javax.swing.JTextField();
        horaSalida = new javax.swing.JLabel();
        puntosHoraSalida = new javax.swing.JLabel();
        horaLlegada = new javax.swing.JLabel();
        precioVuelo = new javax.swing.JLabel();
        precio = new javax.swing.JTextField();
        numeroAsientosFila = new javax.swing.JLabel();
        numAsientosFila = new javax.swing.JTextField();
        numeroFilas = new javax.swing.JLabel();
        numFilas = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        ftVuelos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Busqueda Vuelos");
        setMinimumSize(new java.awt.Dimension(850, 388));
        setResizable(false);
        getContentPane().setLayout(null);

        numeroVuelo.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        numeroVuelo.setForeground(new java.awt.Color(0, 0, 102));
        numeroVuelo.setText("Número de vuelo:");
        getContentPane().add(numeroVuelo);
        numeroVuelo.setBounds(40, 20, 150, 38);

        hrSalida.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        hrSalida.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                hrSalidaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                hrSalidaKeyTyped(evt);
            }
        });
        getContentPane().add(hrSalida);
        hrSalida.setBounds(40, 160, 80, 38);

        hrLlegada.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        hrLlegada.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                hrLlegadaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                hrLlegadaKeyTyped(evt);
            }
        });
        getContentPane().add(hrLlegada);
        hrLlegada.setBounds(40, 260, 80, 38);

        numVuelo.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        numVuelo.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                numVueloKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                numVueloKeyTyped(evt);
            }
        });
        getContentPane().add(numVuelo);
        numVuelo.setBounds(40, 60, 80, 38);

        horaSalida.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        horaSalida.setForeground(new java.awt.Color(0, 0, 102));
        horaSalida.setText("Hora de salida:");
        getContentPane().add(horaSalida);
        horaSalida.setBounds(40, 120, 130, 38);

        puntosHoraSalida.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        puntosHoraSalida.setForeground(new java.awt.Color(0, 0, 102));
        puntosHoraSalida.setText("$");
        puntosHoraSalida.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(puntosHoraSalida);
        puntosHoraSalida.setBounds(370, 60, 20, 40);

        horaLlegada.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        horaLlegada.setForeground(new java.awt.Color(0, 0, 102));
        horaLlegada.setText("Hora de llegada:");
        getContentPane().add(horaLlegada);
        horaLlegada.setBounds(40, 220, 140, 38);

        precioVuelo.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        precioVuelo.setForeground(new java.awt.Color(0, 0, 102));
        precioVuelo.setText("Precio:");
        getContentPane().add(precioVuelo);
        precioVuelo.setBounds(290, 20, 70, 39);

        precio.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        getContentPane().add(precio);
        precio.setBounds(290, 60, 80, 39);

        numeroAsientosFila.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        numeroAsientosFila.setForeground(new java.awt.Color(0, 0, 102));
        numeroAsientosFila.setText("Número de asientos por fila:");
        getContentPane().add(numeroAsientosFila);
        numeroAsientosFila.setBounds(290, 120, 230, 40);

        numAsientosFila.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        getContentPane().add(numAsientosFila);
        numAsientosFila.setBounds(290, 160, 80, 40);

        numeroFilas.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        numeroFilas.setForeground(new java.awt.Color(0, 0, 102));
        numeroFilas.setText("Número de filas:");
        getContentPane().add(numeroFilas);
        numeroFilas.setBounds(290, 220, 202, 40);

        numFilas.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        getContentPane().add(numFilas);
        numFilas.setBounds(290, 260, 80, 40);

        buscar.setBackground(new java.awt.Color(255, 255, 255));
        buscar.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        buscar.setForeground(new java.awt.Color(0, 0, 102));
        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buscarActionPerformed(evt);
            }
        });
        buscar.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                buscarKeyPressed(evt);
            }
        });
        getContentPane().add(buscar);
        buscar.setBounds(740, 320, 90, 23);

        ftVuelos.setBackground(new java.awt.Color(255, 255, 255));
        ftVuelos.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        ftVuelos.setForeground(new java.awt.Color(0, 0, 102));
        ftVuelos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ftVuelos.setText("FOTO");
        ftVuelos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 10));
        getContentPane().add(ftVuelos);
        ftVuelos.setBounds(590, 50, 220, 220);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 850, 360);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void numVueloKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_numVueloKeyPressed
    {//GEN-HEADEREND:event_numVueloKeyPressed
        // KeyPressed es para validar el enter
        Validaciones.enterEntero(this, evt, numVuelo, buscar);
        Validaciones.limite(numVuelo, 5);
    }//GEN-LAST:event_numVueloKeyPressed

    private void numVueloKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_numVueloKeyTyped
    {//GEN-HEADEREND:event_numVueloKeyTyped
        // KeyTyped es para validar entrada de datos
        Validaciones.validaEntero(evt);
    }//GEN-LAST:event_numVueloKeyTyped

    private void buscarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buscarActionPerformed
    {//GEN-HEADEREND:event_buscarActionPerformed
        try
        {
            NodoArbol b;
            b = VentanaPrincipal.aR4.busca(VentanaPrincipal.aR4.getR(), numVuelo.getText());
            if (b != null)
            {
                hrSalida.setText(((Vuelos) b.getHh().getObj()).getHoraSalida());
                hrLlegada.setText(((Vuelos) b.getHh().getObj()).getHoraLlegada());
                precio.setText(String.valueOf(((Vuelos) b.getHh().getObj()).getPrecio()));
                numAsientosFila.setText(String.valueOf(((Vuelos) b.getHh().getObj()).getNumeroAsientosFila()));
                numFilas.setText(String.valueOf(((Vuelos) b.getHh().getObj()).getNumeroFilas()));
                ftVuelos.setIcon(((Vuelos) b.getHh().getObj()).getImagenVue());
            } else
            {
                JOptionPane.showMessageDialog(this, "Dato no registrado", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Seleccione niveles que tengan datos");
            CtrlInterfaz.limpia(numVuelo, precio, numAsientosFila, numFilas);
            CtrlInterfaz.habilita(false, precio, numAsientosFila, numFilas);
            CtrlInterfaz.cambia(numVuelo);
        }
    }//GEN-LAST:event_buscarActionPerformed

    private void buscarKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_buscarKeyPressed
    {//GEN-HEADEREND:event_buscarKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            buscarActionPerformed(null);
        }
    }//GEN-LAST:event_buscarKeyPressed

    private void hrLlegadaKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_hrLlegadaKeyPressed
    {//GEN-HEADEREND:event_hrLlegadaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrLlegadaKeyPressed

    private void hrLlegadaKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_hrLlegadaKeyTyped
    {//GEN-HEADEREND:event_hrLlegadaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_hrLlegadaKeyTyped

    private void hrSalidaKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_hrSalidaKeyPressed
    {//GEN-HEADEREND:event_hrSalidaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrSalidaKeyPressed

    private void hrSalidaKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_hrSalidaKeyTyped
    {//GEN-HEADEREND:event_hrSalidaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_hrSalidaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VentanaBusquedaVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VentanaBusquedaVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VentanaBusquedaVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VentanaBusquedaVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                new VentanaBusquedaVuelos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JLabel ftVuelos;
    private javax.swing.JLabel horaLlegada;
    private javax.swing.JLabel horaSalida;
    private javax.swing.JTextField hrLlegada;
    private javax.swing.JTextField hrSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField numAsientosFila;
    private javax.swing.JTextField numFilas;
    private javax.swing.JTextField numVuelo;
    private javax.swing.JLabel numeroAsientosFila;
    private javax.swing.JLabel numeroFilas;
    private javax.swing.JLabel numeroVuelo;
    private javax.swing.JTextField precio;
    private javax.swing.JLabel precioVuelo;
    private javax.swing.JLabel puntosHoraSalida;
    // End of variables declaration//GEN-END:variables
}
