/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Validaciones;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristopher y Javier
 */
public class VentanaBusquedaAeropuerto extends javax.swing.JFrame
{

    /**
     * Creates new form VentanaAltasAeropuerto
     */
    public VentanaBusquedaAeropuerto()
    {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/Aeropuerto.jpg")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        nombreAeropuerto = new javax.swing.JLabel();
        nomAeropuerto = new javax.swing.JTextField();
        numeroPuertas = new javax.swing.JLabel();
        numPuertas = new javax.swing.JTextField();
        paisAeropuerto = new javax.swing.JLabel();
        pais = new javax.swing.JTextField();
        claveAeropuerto = new javax.swing.JLabel();
        clave = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        ftAeropuerto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Busqueda Aeropuertos");
        setMinimumSize(new java.awt.Dimension(615, 460));
        setResizable(false);
        getContentPane().setLayout(null);

        nombreAeropuerto.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        nombreAeropuerto.setForeground(new java.awt.Color(0, 0, 102));
        nombreAeropuerto.setText("Nombre del aeropuerto:");
        getContentPane().add(nombreAeropuerto);
        nombreAeropuerto.setBounds(40, 20, 206, 38);

        nomAeropuerto.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        nomAeropuerto.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                nomAeropuertoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                nomAeropuertoKeyTyped(evt);
            }
        });
        getContentPane().add(nomAeropuerto);
        nomAeropuerto.setBounds(40, 60, 263, 38);

        numeroPuertas.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        numeroPuertas.setForeground(new java.awt.Color(0, 0, 102));
        numeroPuertas.setText("Número de puertas:");
        getContentPane().add(numeroPuertas);
        numeroPuertas.setBounds(40, 320, 159, 38);

        numPuertas.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        getContentPane().add(numPuertas);
        numPuertas.setBounds(40, 360, 60, 38);

        paisAeropuerto.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        paisAeropuerto.setForeground(new java.awt.Color(0, 0, 102));
        paisAeropuerto.setText("País:");
        getContentPane().add(paisAeropuerto);
        paisAeropuerto.setBounds(40, 120, 43, 40);

        pais.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        getContentPane().add(pais);
        pais.setBounds(40, 160, 260, 39);

        claveAeropuerto.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        claveAeropuerto.setForeground(new java.awt.Color(0, 0, 102));
        claveAeropuerto.setText("Clave:");
        getContentPane().add(claveAeropuerto);
        claveAeropuerto.setBounds(40, 220, 59, 39);

        clave.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        getContentPane().add(clave);
        clave.setBounds(40, 260, 260, 39);

        buscar.setBackground(new java.awt.Color(255, 255, 255));
        buscar.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        buscar.setForeground(new java.awt.Color(0, 0, 102));
        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buscarActionPerformed(evt);
            }
        });
        buscar.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                buscarKeyPressed(evt);
            }
        });
        getContentPane().add(buscar);
        buscar.setBounds(510, 390, 77, 23);

        ftAeropuerto.setBackground(new java.awt.Color(255, 255, 255));
        ftAeropuerto.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        ftAeropuerto.setForeground(new java.awt.Color(0, 0, 102));
        ftAeropuerto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ftAeropuerto.setText("FOTO");
        ftAeropuerto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 10));
        getContentPane().add(ftAeropuerto);
        ftAeropuerto.setBounds(350, 60, 220, 220);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 620, 440);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nomAeropuertoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nomAeropuertoKeyPressed
    {//GEN-HEADEREND:event_nomAeropuertoKeyPressed
        // KeyPressed es para validar el enter
        Validaciones.enter(this, evt, buscar);
        Validaciones.limite(nomAeropuerto, 30);
    }//GEN-LAST:event_nomAeropuertoKeyPressed

    private void nomAeropuertoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nomAeropuertoKeyTyped
    {//GEN-HEADEREND:event_nomAeropuertoKeyTyped
        // KeyTyped es para validar entrada de datos
        Validaciones.validaAlfabeticos(evt);
    }//GEN-LAST:event_nomAeropuertoKeyTyped

    private void buscarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buscarActionPerformed
    {//GEN-HEADEREND:event_buscarActionPerformed
        try
        {
            NodoArbol b;
            b = VentanaPrincipal.aR1.busca(VentanaPrincipal.aR1.getR(), nomAeropuerto.getText());
            if (b != null)
            {
                pais.setText(((Aeropuerto) b.getHh().getObj()).getPais());
                clave.setText(((Aeropuerto) b.getHh().getObj()).getClave());
                numPuertas.setText(String.valueOf(((Aeropuerto) b.getHh().getObj()).getNumeroPuertas()));
                ftAeropuerto.setIcon(((Aeropuerto) b.getHh().getObj()).getImagenAer());
            } else
            {
                JOptionPane.showMessageDialog(this, "Dato no registrado", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Error", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
            CtrlInterfaz.limpia(nomAeropuerto, numPuertas, pais, clave);
            CtrlInterfaz.habilita(false, numPuertas, pais, clave);
            CtrlInterfaz.cambia(nomAeropuerto);
        }
    }//GEN-LAST:event_buscarActionPerformed

    private void buscarKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_buscarKeyPressed
    {//GEN-HEADEREND:event_buscarKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            buscarActionPerformed(null);
        }
    }//GEN-LAST:event_buscarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VentanaBusquedaAeropuerto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() ->
        {
            new VentanaBusquedaAeropuerto().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JTextField clave;
    private javax.swing.JLabel claveAeropuerto;
    private javax.swing.JLabel ftAeropuerto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nomAeropuerto;
    private javax.swing.JLabel nombreAeropuerto;
    private javax.swing.JTextField numPuertas;
    private javax.swing.JLabel numeroPuertas;
    private javax.swing.JTextField pais;
    private javax.swing.JLabel paisAeropuerto;
    // End of variables declaration//GEN-END:variables
}
