/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensaje;
import cjb.ci.Validaciones;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristopher y Javier
 */
public class VentanaModCompania extends javax.swing.JFrame
{

    public Nodo n2;

    /**
     * Creates new form VentanaAltasAeropuerto
     */
    public VentanaModCompania()
    {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/Compania.jpg")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        nombreCompania = new javax.swing.JLabel();
        nomCompania = new javax.swing.JTextField();
        urlCompania = new javax.swing.JLabel();
        url = new javax.swing.JTextField();
        telefonoCompania = new javax.swing.JLabel();
        telefono1 = new javax.swing.JTextField();
        telefono2 = new javax.swing.JTextField();
        agregarImagen = new javax.swing.JButton();
        correoElectronico = new javax.swing.JLabel();
        correoElec = new javax.swing.JTextField();
        aceptar = new javax.swing.JButton();
        ftCompania = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificaciones Compañias");
        setMinimumSize(new java.awt.Dimension(925, 420));
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        nombreCompania.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        nombreCompania.setForeground(new java.awt.Color(0, 0, 102));
        nombreCompania.setText("Nombre de la compañia:");
        getContentPane().add(nombreCompania);
        nombreCompania.setBounds(40, 60, 230, 38);

        nomCompania.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        nomCompania.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                nomCompaniaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                nomCompaniaKeyTyped(evt);
            }
        });
        getContentPane().add(nomCompania);
        nomCompania.setBounds(40, 100, 260, 38);

        urlCompania.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        urlCompania.setForeground(new java.awt.Color(0, 0, 102));
        urlCompania.setText("URL:");
        getContentPane().add(urlCompania);
        urlCompania.setBounds(40, 210, 80, 38);

        url.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        url.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                urlKeyPressed(evt);
            }
        });
        getContentPane().add(url);
        url.setBounds(40, 250, 260, 38);

        telefonoCompania.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        telefonoCompania.setForeground(new java.awt.Color(0, 0, 102));
        telefonoCompania.setText("Teléfono:");
        getContentPane().add(telefonoCompania);
        telefonoCompania.setBounds(350, 60, 120, 39);

        telefono1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        telefono1.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                telefono1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                telefono1KeyTyped(evt);
            }
        });
        getContentPane().add(telefono1);
        telefono1.setBounds(350, 100, 50, 39);

        telefono2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        telefono2.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                telefono2KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                telefono2KeyTyped(evt);
            }
        });
        getContentPane().add(telefono2);
        telefono2.setBounds(410, 100, 200, 39);

        agregarImagen.setBackground(new java.awt.Color(255, 255, 255));
        agregarImagen.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        agregarImagen.setForeground(new java.awt.Color(0, 0, 102));
        agregarImagen.setText("Agregar");
        agregarImagen.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                agregarImagenActionPerformed(evt);
            }
        });
        agregarImagen.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                agregarImagenKeyPressed(evt);
            }
        });
        getContentPane().add(agregarImagen);
        agregarImagen.setBounds(720, 270, 90, 23);

        correoElectronico.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        correoElectronico.setForeground(new java.awt.Color(0, 0, 102));
        correoElectronico.setText("Correo electrónico:");
        getContentPane().add(correoElectronico);
        correoElectronico.setBounds(350, 210, 180, 39);

        correoElec.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        correoElec.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                correoElecKeyPressed(evt);
            }
        });
        getContentPane().add(correoElec);
        correoElec.setBounds(350, 250, 260, 39);

        aceptar.setBackground(new java.awt.Color(255, 255, 255));
        aceptar.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        aceptar.setForeground(new java.awt.Color(0, 0, 102));
        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                aceptarActionPerformed(evt);
            }
        });
        aceptar.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                aceptarKeyPressed(evt);
            }
        });
        getContentPane().add(aceptar);
        aceptar.setBounds(800, 340, 90, 23);

        ftCompania.setBackground(new java.awt.Color(255, 255, 255));
        ftCompania.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        ftCompania.setForeground(new java.awt.Color(0, 0, 102));
        ftCompania.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ftCompania.setText("FOTO");
        ftCompania.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 10));
        getContentPane().add(ftCompania);
        ftCompania.setBounds(650, 30, 220, 220);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 910, 390);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        Nodo n3 = VentanaModificaCompania.arrCom[0];
        nomCompania.setText(((Compania) n3.getObj()).getNombreCompania());
        url.setText(((Compania) n3.getObj()).getuRL());
        telefono1.setText(String.valueOf(((Compania) n3.getObj()).getTelefono1()));
        telefono2.setText(String.valueOf(((Compania) n3.getObj()).getTelefono2()));
        correoElec.setText(((Compania) n3.getObj()).getCorreoElectronico());
        ftCompania.setIcon(((Compania) n3.getObj()).getImagenCom());
    }//GEN-LAST:event_formWindowOpened

    private void aceptarKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_aceptarKeyPressed
    {//GEN-HEADEREND:event_aceptarKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            aceptarActionPerformed(null);
        }
    }//GEN-LAST:event_aceptarKeyPressed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_aceptarActionPerformed
    {//GEN-HEADEREND:event_aceptarActionPerformed
        try
        {
            String numeroCadeda1 = telefono1.getText();
            String numeroCadeda2 = telefono2.getText();
            long numeroEntero1 = Integer.parseInt(numeroCadeda1);
            long numeroEntero2 = Integer.parseInt(numeroCadeda2);
            Compania cpn = new Compania(nomCompania.getText(), url.getText(), numeroEntero1, numeroEntero2, correoElec.getText(), ftCompania.getIcon());
            Nodo nd = new Nodo(cpn, nomCompania.getText());
            String s[] = new String[3];
            s[0] = VentanaModificaCompania.sCom[0];
            s[1] = VentanaModificaCompania.sCom[1];
            s[2] = nomCompania.getText();
            VentanaPrincipal.r = ManipulaMultista.inserta(VentanaPrincipal.r, nd, s, 0);
            NodoArbol ndA = new NodoArbol(nomCompania.getText());
            ndA.setHh(nd);
            VentanaPrincipal.aR3.setR(VentanaPrincipal.aR3.inserta(VentanaPrincipal.aR3.getR(), ndA));
            Mensaje.exito(this, "Modificaciones guardadas");
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Error", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
            CtrlInterfaz.limpia(nomCompania, url, telefono1, correoElec);
            CtrlInterfaz.habilita(false, url, telefono1, correoElec);
            ftCompania.setIcon(null);
            CtrlInterfaz.cambia(nomCompania);
        }
    }//GEN-LAST:event_aceptarActionPerformed

    private void telefono1KeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_telefono1KeyTyped
    {//GEN-HEADEREND:event_telefono1KeyTyped
        Validaciones.validaEntero(evt);
    }//GEN-LAST:event_telefono1KeyTyped

    private void telefono1KeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_telefono1KeyPressed
    {//GEN-HEADEREND:event_telefono1KeyPressed
        Validaciones.limite(telefono1, 3);
        Validaciones.enterEntero(this, evt, telefono1, telefono2);
    }//GEN-LAST:event_telefono1KeyPressed

    private void correoElecKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_correoElecKeyPressed
    {//GEN-HEADEREND:event_correoElecKeyPressed
        Validaciones.enter(this, evt, agregarImagen);
        Validaciones.limite(correoElec, 30);
    }//GEN-LAST:event_correoElecKeyPressed

    private void urlKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_urlKeyPressed
    {//GEN-HEADEREND:event_urlKeyPressed
        Validaciones.enter(this, evt, telefono1);
        Validaciones.limite(url, 40);
    }//GEN-LAST:event_urlKeyPressed

    private void nomCompaniaKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nomCompaniaKeyTyped
    {//GEN-HEADEREND:event_nomCompaniaKeyTyped
        // KeyTyped es para validar entrada de datos
        Validaciones.validaAlfabeticos(evt);
    }//GEN-LAST:event_nomCompaniaKeyTyped

    private void nomCompaniaKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nomCompaniaKeyPressed
    {//GEN-HEADEREND:event_nomCompaniaKeyPressed
        // KeyPressed es para validar el enter
        Validaciones.enter(this, evt, url);
        Validaciones.limite(nomCompania, 30);
    }//GEN-LAST:event_nomCompaniaKeyPressed

    private void agregarImagenActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_agregarImagenActionPerformed
    {//GEN-HEADEREND:event_agregarImagenActionPerformed
        new VentanaFotosCarga(ftCompania).setVisible(true);
    }//GEN-LAST:event_agregarImagenActionPerformed

    private void agregarImagenKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_agregarImagenKeyPressed
    {//GEN-HEADEREND:event_agregarImagenKeyPressed
        new VentanaFotosCarga(ftCompania).setVisible(true);
    }//GEN-LAST:event_agregarImagenKeyPressed

    private void telefono2KeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_telefono2KeyPressed
    {//GEN-HEADEREND:event_telefono2KeyPressed
        Validaciones.limite(telefono1, 7);
        Validaciones.enterEntero(this, evt, telefono1, correoElec);
    }//GEN-LAST:event_telefono2KeyPressed

    private void telefono2KeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_telefono2KeyTyped
    {//GEN-HEADEREND:event_telefono2KeyTyped
        Validaciones.validaEntero(evt);
    }//GEN-LAST:event_telefono2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VentanaModCompania.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VentanaModCompania.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VentanaModCompania.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VentanaModCompania.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                new VentanaModCompania().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JButton agregarImagen;
    private javax.swing.JTextField correoElec;
    private javax.swing.JLabel correoElectronico;
    private javax.swing.JLabel ftCompania;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nomCompania;
    private javax.swing.JLabel nombreCompania;
    private javax.swing.JTextField telefono1;
    private javax.swing.JTextField telefono2;
    private javax.swing.JLabel telefonoCompania;
    private javax.swing.JTextField url;
    private javax.swing.JLabel urlCompania;
    // End of variables declaration//GEN-END:variables
}
