/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensaje;
import cjb.ci.Validaciones;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristopher y Javier
 */
public class VentanaModAeropuerto extends javax.swing.JFrame
{

    /**
     * Creates new form VentanaAltasAeropuerto
     */
    public VentanaModAeropuerto()
    {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/Aeropuerto.jpg")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        nombreAeropuerto = new javax.swing.JLabel();
        nomAeropuerto = new javax.swing.JTextField();
        numeroPuertas = new javax.swing.JLabel();
        numPuertas = new javax.swing.JTextField();
        paisAeropuerto = new javax.swing.JLabel();
        pais = new javax.swing.JTextField();
        claveAeropuerto = new javax.swing.JLabel();
        clave = new javax.swing.JTextField();
        aceptar = new javax.swing.JButton();
        ftAeropuerto = new javax.swing.JLabel();
        agregarImagen = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificaciones Aeropuertos");
        setMinimumSize(new java.awt.Dimension(615, 460));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        nombreAeropuerto.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        nombreAeropuerto.setForeground(new java.awt.Color(0, 0, 102));
        nombreAeropuerto.setText("Nombre del aeropuerto:");
        getContentPane().add(nombreAeropuerto);
        nombreAeropuerto.setBounds(40, 20, 206, 38);

        nomAeropuerto.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        nomAeropuerto.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                nomAeropuertoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                nomAeropuertoKeyTyped(evt);
            }
        });
        getContentPane().add(nomAeropuerto);
        nomAeropuerto.setBounds(40, 60, 263, 38);

        numeroPuertas.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        numeroPuertas.setForeground(new java.awt.Color(0, 0, 102));
        numeroPuertas.setText("Número de puertas:");
        getContentPane().add(numeroPuertas);
        numeroPuertas.setBounds(40, 320, 159, 38);

        numPuertas.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        numPuertas.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                numPuertasKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                numPuertasKeyTyped(evt);
            }
        });
        getContentPane().add(numPuertas);
        numPuertas.setBounds(40, 360, 60, 38);

        paisAeropuerto.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        paisAeropuerto.setForeground(new java.awt.Color(0, 0, 102));
        paisAeropuerto.setText("País:");
        getContentPane().add(paisAeropuerto);
        paisAeropuerto.setBounds(40, 120, 43, 40);

        pais.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        pais.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                paisKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                paisKeyTyped(evt);
            }
        });
        getContentPane().add(pais);
        pais.setBounds(40, 160, 260, 39);

        claveAeropuerto.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        claveAeropuerto.setForeground(new java.awt.Color(0, 0, 102));
        claveAeropuerto.setText("Clave:");
        getContentPane().add(claveAeropuerto);
        claveAeropuerto.setBounds(40, 220, 59, 39);

        clave.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        clave.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                claveKeyPressed(evt);
            }
        });
        getContentPane().add(clave);
        clave.setBounds(40, 260, 260, 39);

        aceptar.setBackground(new java.awt.Color(255, 255, 255));
        aceptar.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        aceptar.setForeground(new java.awt.Color(0, 0, 102));
        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                aceptarActionPerformed(evt);
            }
        });
        aceptar.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                aceptarKeyPressed(evt);
            }
        });
        getContentPane().add(aceptar);
        aceptar.setBounds(510, 390, 83, 23);

        ftAeropuerto.setBackground(new java.awt.Color(255, 255, 255));
        ftAeropuerto.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        ftAeropuerto.setForeground(new java.awt.Color(0, 0, 102));
        ftAeropuerto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ftAeropuerto.setText("FOTO");
        ftAeropuerto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 10));
        getContentPane().add(ftAeropuerto);
        ftAeropuerto.setBounds(350, 60, 220, 220);

        agregarImagen.setBackground(new java.awt.Color(255, 255, 255));
        agregarImagen.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        agregarImagen.setForeground(new java.awt.Color(0, 0, 102));
        agregarImagen.setText("Agregar");
        agregarImagen.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                agregarImagenActionPerformed(evt);
            }
        });
        agregarImagen.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                agregarImagenKeyPressed(evt);
            }
        });
        getContentPane().add(agregarImagen);
        agregarImagen.setBounds(420, 300, 90, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 620, 440);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nomAeropuertoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nomAeropuertoKeyPressed
    {//GEN-HEADEREND:event_nomAeropuertoKeyPressed
        // KeyPressed es para validar el enter
        Validaciones.enter(this, evt, pais);
        Validaciones.limite(nomAeropuerto, 30);
    }//GEN-LAST:event_nomAeropuertoKeyPressed

    private void nomAeropuertoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nomAeropuertoKeyTyped
    {//GEN-HEADEREND:event_nomAeropuertoKeyTyped
        // KeyTyped es para validar entrada de datos
        Validaciones.validaAlfabeticos(evt);
    }//GEN-LAST:event_nomAeropuertoKeyTyped

    private void numPuertasKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_numPuertasKeyPressed
    {//GEN-HEADEREND:event_numPuertasKeyPressed
        Validaciones.enterEntero(this, evt, numPuertas, agregarImagen);
        Validaciones.limite(numPuertas, 3);
    }//GEN-LAST:event_numPuertasKeyPressed

    private void numPuertasKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_numPuertasKeyTyped
    {//GEN-HEADEREND:event_numPuertasKeyTyped
        Validaciones.validaEntero(evt);
    }//GEN-LAST:event_numPuertasKeyTyped

    private void paisKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_paisKeyPressed
    {//GEN-HEADEREND:event_paisKeyPressed
        Validaciones.enter(this, evt, clave);
        Validaciones.limite(pais, 30);
    }//GEN-LAST:event_paisKeyPressed

    private void paisKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_paisKeyTyped
    {//GEN-HEADEREND:event_paisKeyTyped
        Validaciones.validaAlfabeticos(evt);
    }//GEN-LAST:event_paisKeyTyped

    private void claveKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_claveKeyPressed
    {//GEN-HEADEREND:event_claveKeyPressed
        Validaciones.enter(this, evt, numPuertas);
        Validaciones.limite(clave, 30);
    }//GEN-LAST:event_claveKeyPressed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_aceptarActionPerformed
    {//GEN-HEADEREND:event_aceptarActionPerformed
        try
        {
            String numeroCadeda = numPuertas.getText();
            int numeroEntero = Integer.parseInt(numeroCadeda);
            Aeropuerto arp = new Aeropuerto(nomAeropuerto.getText(), numeroEntero, pais.getText(), clave.getText(), ftAeropuerto.getIcon());
            Nodo nd = new Nodo(arp, nomAeropuerto.getText());
            String s[] = new String[1];
            s[0] = nomAeropuerto.getText();
            VentanaPrincipal.r = ManipulaMultista.inserta(VentanaPrincipal.r, nd, s, 0);
            NodoArbol ndA = new NodoArbol(nomAeropuerto.getText());
            ndA.setHh(nd);
            VentanaPrincipal.aR1.setR(VentanaPrincipal.aR1.inserta(VentanaPrincipal.aR1.getR(), ndA));
            Mensaje.exito(this, "Modificaciones guardadas");
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Error", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
            CtrlInterfaz.limpia(nomAeropuerto, numPuertas, pais, clave);
            CtrlInterfaz.habilita(false, numPuertas, pais, clave);
            ftAeropuerto.setIcon(null);
            CtrlInterfaz.cambia(nomAeropuerto);
        }
    }//GEN-LAST:event_aceptarActionPerformed

    private void aceptarKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_aceptarKeyPressed
    {//GEN-HEADEREND:event_aceptarKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            aceptarActionPerformed(null);
        }
    }//GEN-LAST:event_aceptarKeyPressed

    private void agregarImagenActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_agregarImagenActionPerformed
    {//GEN-HEADEREND:event_agregarImagenActionPerformed
        new VentanaFotosCarga(ftAeropuerto).setVisible(true);
    }//GEN-LAST:event_agregarImagenActionPerformed

    private void agregarImagenKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_agregarImagenKeyPressed
    {//GEN-HEADEREND:event_agregarImagenKeyPressed
        new VentanaFotosCarga(ftAeropuerto).setVisible(true);
    }//GEN-LAST:event_agregarImagenKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        Nodo n1 = VentanaModificaAeropuerto.arrAer[0];
        nomAeropuerto.setText(((Aeropuerto) n1.getObj()).getNombreAeropuerto());
        pais.setText(((Aeropuerto) n1.getObj()).getPais());
        clave.setText(((Aeropuerto) n1.getObj()).getClave());
        numPuertas.setText(String.valueOf(((Aeropuerto) n1.getObj()).getNumeroPuertas()));
        ftAeropuerto.setIcon(((Aeropuerto) n1.getObj()).getImagenAer());
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VentanaModAeropuerto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() ->
        {
            new VentanaModAeropuerto().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JButton agregarImagen;
    private javax.swing.JTextField clave;
    private javax.swing.JLabel claveAeropuerto;
    private javax.swing.JLabel ftAeropuerto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nomAeropuerto;
    private javax.swing.JLabel nombreAeropuerto;
    private javax.swing.JTextField numPuertas;
    private javax.swing.JLabel numeroPuertas;
    private javax.swing.JTextField pais;
    private javax.swing.JLabel paisAeropuerto;
    // End of variables declaration//GEN-END:variables
}
