/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Validaciones;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristopher y Javier
 */
public class VentanaBusquedaDestino extends javax.swing.JFrame
{

    /**
     * Creates new form VentanaAltasAeropuerto
     */
    public VentanaBusquedaDestino()
    {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/Destino.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        destinoDestino = new javax.swing.JLabel();
        buscar = new javax.swing.JButton();
        destino = new javax.swing.JTextField();
        ftDestino = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Busqueda Destinos");
        setMinimumSize(new java.awt.Dimension(630, 378));
        getContentPane().setLayout(null);

        destinoDestino.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        destinoDestino.setForeground(new java.awt.Color(0, 0, 102));
        destinoDestino.setText("Destino:");
        getContentPane().add(destinoDestino);
        destinoDestino.setBounds(40, 90, 174, 38);

        buscar.setBackground(new java.awt.Color(255, 255, 255));
        buscar.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        buscar.setForeground(new java.awt.Color(0, 0, 102));
        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buscarActionPerformed(evt);
            }
        });
        buscar.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                buscarKeyPressed(evt);
            }
        });
        getContentPane().add(buscar);
        buscar.setBounds(510, 300, 77, 23);

        destino.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        destino.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                destinoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                destinoKeyTyped(evt);
            }
        });
        getContentPane().add(destino);
        destino.setBounds(40, 130, 260, 38);

        ftDestino.setBackground(new java.awt.Color(255, 255, 255));
        ftDestino.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        ftDestino.setForeground(new java.awt.Color(0, 0, 102));
        ftDestino.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ftDestino.setText("FOTO");
        ftDestino.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 10));
        getContentPane().add(ftDestino);
        ftDestino.setBounds(350, 30, 220, 220);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1200, 100));
        jLabel1.setMinimumSize(new java.awt.Dimension(1200, 100));
        jLabel1.setPreferredSize(new java.awt.Dimension(1200, 100));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 620, 340);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void destinoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_destinoKeyPressed
    {//GEN-HEADEREND:event_destinoKeyPressed
        // KeyPressed es para validar el enter
        Validaciones.enter(this, evt, buscar);
        Validaciones.limite(destino, 30);
    }//GEN-LAST:event_destinoKeyPressed

    private void destinoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_destinoKeyTyped
    {//GEN-HEADEREND:event_destinoKeyTyped
        // KeyTyped es para validar entrada de datos
        Validaciones.validaAlfabeticos(evt);
    }//GEN-LAST:event_destinoKeyTyped

    private void buscarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buscarActionPerformed
    {//GEN-HEADEREND:event_buscarActionPerformed
        try
        {
            NodoArbol b;
            b = VentanaPrincipal.aR2.busca(VentanaPrincipal.aR2.getR(), destino.getText());
            if (b != null)
            {
                ftDestino.setIcon(((Destino) b.getHh().getObj()).getImagenDest());
            } else
            {
                JOptionPane.showMessageDialog(this, "Dato no registrado", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Error", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
            CtrlInterfaz.limpia(destino);
            CtrlInterfaz.cambia(destino);
        }
    }//GEN-LAST:event_buscarActionPerformed

    private void buscarKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_buscarKeyPressed
    {//GEN-HEADEREND:event_buscarKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            buscarActionPerformed(null);
        }
    }//GEN-LAST:event_buscarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VentanaBusquedaDestino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VentanaBusquedaDestino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VentanaBusquedaDestino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VentanaBusquedaDestino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                new VentanaBusquedaDestino().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JTextField destino;
    private javax.swing.JLabel destinoDestino;
    private javax.swing.JLabel ftDestino;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
