/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensaje;
import cjb.ci.Validaciones;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristopher y Javier
 */
public class VentanaModDestino extends javax.swing.JFrame
{

    /**
     * Creates new form VentanaAltasAeropuerto
     */
    public VentanaModDestino()
    {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/Destino.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        destinoDestino = new javax.swing.JLabel();
        aceptar = new javax.swing.JButton();
        destino = new javax.swing.JTextField();
        ftDestino = new javax.swing.JLabel();
        agregarImagen = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificaciones Destinos");
        setMinimumSize(new java.awt.Dimension(630, 430));
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        destinoDestino.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        destinoDestino.setForeground(new java.awt.Color(0, 0, 102));
        destinoDestino.setText("Destino:");
        getContentPane().add(destinoDestino);
        destinoDestino.setBounds(40, 120, 174, 38);

        aceptar.setBackground(new java.awt.Color(255, 255, 255));
        aceptar.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        aceptar.setForeground(new java.awt.Color(0, 0, 102));
        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                aceptarActionPerformed(evt);
            }
        });
        aceptar.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                aceptarKeyPressed(evt);
            }
        });
        getContentPane().add(aceptar);
        aceptar.setBounds(510, 350, 83, 23);

        destino.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        destino.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                destinoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                destinoKeyTyped(evt);
            }
        });
        getContentPane().add(destino);
        destino.setBounds(40, 160, 260, 38);

        ftDestino.setBackground(new java.awt.Color(255, 255, 255));
        ftDestino.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        ftDestino.setForeground(new java.awt.Color(0, 0, 102));
        ftDestino.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ftDestino.setText("FOTO");
        ftDestino.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 10));
        getContentPane().add(ftDestino);
        ftDestino.setBounds(350, 30, 220, 220);

        agregarImagen.setBackground(new java.awt.Color(255, 255, 255));
        agregarImagen.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        agregarImagen.setForeground(new java.awt.Color(0, 0, 102));
        agregarImagen.setText("Agregar");
        agregarImagen.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                agregarImagenActionPerformed(evt);
            }
        });
        agregarImagen.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                agregarImagenKeyPressed(evt);
            }
        });
        getContentPane().add(agregarImagen);
        agregarImagen.setBounds(420, 270, 90, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1200, 100));
        jLabel1.setMinimumSize(new java.awt.Dimension(1200, 100));
        jLabel1.setPreferredSize(new java.awt.Dimension(1200, 100));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 620, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void destinoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_destinoKeyPressed
    {//GEN-HEADEREND:event_destinoKeyPressed
        // KeyPressed es para validar el enter
        Validaciones.enter(this, evt, agregarImagen);
        Validaciones.limite(destino, 30);
    }//GEN-LAST:event_destinoKeyPressed

    private void destinoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_destinoKeyTyped
    {//GEN-HEADEREND:event_destinoKeyTyped
        // KeyTyped es para validar entrada de datos
        Validaciones.validaAlfabeticos(evt);
    }//GEN-LAST:event_destinoKeyTyped

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_aceptarActionPerformed
    {//GEN-HEADEREND:event_aceptarActionPerformed
        try
        {
            Destino dst = new Destino(destino.getText(), ftDestino.getIcon());
            Nodo nd = new Nodo(dst, destino.getText());
            String s[] = new String[2];
            s[0] = VentanaModificaDestino.sDes[0];
            s[1] = destino.getText();
            VentanaPrincipal.r = ManipulaMultista.inserta(VentanaPrincipal.r, nd, s, 0);
            NodoArbol ndA = new NodoArbol(destino.getText());
            ndA.setHh(nd);
            VentanaPrincipal.aR2.setR(VentanaPrincipal.aR2.inserta(VentanaPrincipal.aR2.getR(), ndA));
            Mensaje.exito(this, "Modificaciones guardadas");
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Error", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
            CtrlInterfaz.limpia(destino);
            ftDestino.setIcon(null);
            CtrlInterfaz.cambia(destino);
        }
    }//GEN-LAST:event_aceptarActionPerformed

    private void aceptarKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_aceptarKeyPressed
    {//GEN-HEADEREND:event_aceptarKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            aceptarActionPerformed(null);
        }
    }//GEN-LAST:event_aceptarKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        Nodo n2 = VentanaModificaDestino.arrDes[0];
        destino.setText(((Destino) n2.getObj()).getAeropuertoDestino());
        ftDestino.setIcon(((Destino) n2.getObj()).getImagenDest());
    }//GEN-LAST:event_formWindowOpened

    private void agregarImagenActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_agregarImagenActionPerformed
    {//GEN-HEADEREND:event_agregarImagenActionPerformed
        new VentanaFotosCarga(ftDestino).setVisible(true);
    }//GEN-LAST:event_agregarImagenActionPerformed

    private void agregarImagenKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_agregarImagenKeyPressed
    {//GEN-HEADEREND:event_agregarImagenKeyPressed
        new VentanaFotosCarga(ftDestino).setVisible(true);
    }//GEN-LAST:event_agregarImagenKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VentanaModDestino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VentanaModDestino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VentanaModDestino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VentanaModDestino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                new VentanaModDestino().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JButton agregarImagen;
    private javax.swing.JTextField destino;
    private javax.swing.JLabel destinoDestino;
    private javax.swing.JLabel ftDestino;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
